name: Unittests using abcvoting installed from pip, run daily

on:
  schedule:
    - cron: '* 5 * * *'  # every day at 5:00

jobs:
  unittests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install abcvoting
        pip install gmpy2
        pip install ortools
        pip install gurobipy
        pip install pytest

    - name: Test with pytest
      run: |
        rm -r abcvoting
        ls
        pytest -v --tb=long -m "not mipgurobi and (not gurobipy or not slow) and (not mipcbc or not slow) and (not ortools or not slow) and not veryslow" -ra tests/
